[package]
name = "Glow in the Dahrk"
description = "Windows transition to glowing versions at night."
authors = [
	"Melchior Dahrk",
	"NullCascade",
]
version = "3.3.0"

[dependencies.mwse]
buildnumber = 3228
